export const  logo =  require('../../assets/images/logo.png')  
export const jobMarker = require('../../assets/images/jobs.png')
export const userMarker = require('../../assets/images/marker.svg')
export const AiIcon = require('../../assets/images/AI.png')
export const AiWoman = require('../../assets/images/aiwoman.png')